### PR TITLE
Virtual Entity Support

### PR DESCRIPTION
**Pull request by AN-BC**
To create a virtual entity, you setup a base view. The only requirement is that there is a stable, non-repeating primary key in the base view, it can be derived from any source within the view. Here is an example:

```
CREATE VIEW crm.vwDealsWithAccountInfo 
AS
SELECT 
	d.*, 
	a.Name, 
	a.TaxID, 
	a.Acronym, 
	a.Description AccountDescription 
FROM
	crm.vwDeals d 
INNER JOIN 
	crm.vwAccounts a ON d.AccountID=a.ID
```

Once you have a view like this defined, you then insert a row into the `Entity` table with this helper sp like so:

```
EXEC __mj.spCreateVirtualEntity @Name='Deals with Account Info',@BaseView='vwDealsWithAccountInfo',@SchemaName='crm',@PrimaryKeyFieldName='ID'
```  
Then, you run CodeGen and it picks up the new virtual entity and **maintain it for you** automatically as the fields in the virtual entity change over time.

### CODE REVIEW

**Comment by AN-BC** [comment]
@cadam11 @dray-mc @hiltongr @JS-BC in case you already looked at this PR before 7:50 AM on Sat (central time), I modified the above comment and added a commit which includes an additional migration that has a helper `stored proc` that makes creating the sp initially way easier for admins. We can of course put a UI around this eventually if we want.

**Comment by AN-BC** [comment]
@cadam11 one question - for the last thing I did here with the helper SP, since it is a new SP I wasn't sure if I should add to `MJ_BASE_BEFORE.sql` or not?

**Comment by dray-mc** [comment]
This process makes sense and looks good to me. Removes the need for an empty, structural placeholder table behind the entity like I'm doing right now.

Does CodeGen create entity field records off the view? So changing the base view fields would mean running CodeGen to pick them up?

I'm going to have to go back and confirm if my current reporting entities actually have unique IDs... They all have an ID field marked as primary keys on their placeholder tables, but I'm questioning whether I actually used a unique value in my view logic or if there would be repeats based on my JOINs. (not a problem to make them unique, just something to keep in mind as long as that's required)

**Comment by AN-BC** [comment]
That's right, CodeGen automatically will keep the metadata in sync with the BaseView you specify. The unique ID thing is important so you can look at records when clicking from a view and other scenarios.

________________________________

**Comment by JS-BC** [comment]
@AN-BC How does CRUD operations on a virtual entity look like? e.g. In your above example, if I create a DealsWithAccountInfo  entity, change the description then attempt to save, would the underlying account record's description change?

**Comment by AN-BC** [comment]
Virtual entities are read only





________________________________

**Comment by cadam11** [comment]
> @cadam11 one question - for the last thing I did here with the helper SP, since it is a new SP I wasn't sure if I should add to `MJ_BASE_BEFORE.sql` or not?

That script is optionally (included by default in config.json) run before every CodeGen. In theory, CodeGen should expect that the migrations completely prepare the database for a CodeGen run, so there should be no need to have `MJ_BASE_BEFORE` at all. However, if we do choose to run it, then we have to be sure that it's not undermining any changes made by migrations– i.e. if a migration creates a SP with a specific definition, the MJ_BASE_BEFORE script should not drop/re-create that SP.

Ideally, we remove MJ_BASE_BEFORE entirely so we can count on the migrations being the only source of truth for the required pre-CodeGen state of the database.

Having pre-CodeGen scripts run per config.json is handy, mind you. I use it in a test environment to seed the database with some test data if not already present (which comes after migrations but before CodeGen).

**Pull request merged**
